apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-myapp
  labels:
    app: myapp
    type: deployment-front-end
spec:
  template:
  # template of the pod which needs to be created by replica set
    metadata:
       name: pod-myapp
       labels:
         app: myapp
         type: front-end
    spec:
      containers:
         -  name: nginx
            image: nginx
  replicas: 2
  selector:
     matchLabels:
        type: front-end