apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-apps
spec:
  containers:
  - name: postgres
    image: postgres:9.4
    ports:
     - containerPort: 5432