apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-apps
spec:
  ports:
  - port: 6379
    name: redis
    targetPort: 6379
  selector:
     name: redis-pod
     app: demo-voting-apps