apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 8089
  selector:
    name: voting-app-pod
    app: demo-voting-apps